"""
Self-consistency validation for svforge-generated VCFs

Reads a VCF produced by ``svforge gen`` / ``gen-pair`` and, for every
record tagged ``INFO/SVFORGE_SOURCE=gnomad`` or ``INFO/SVFORGE_SOURCE=blacklist``,
asserts that the record's ``CHROM/POS/END`` matches an entry in the
corresponding bundled mini catalog. The check is deterministic and
tolerance-free: either the VCF was generated by this svforge build and
matches, or it didn't and doesn't
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pysam

from svforge.core.injection_catalogs import (
    BlacklistEntry,
    GnomadEntry,
    load_blacklist_catalog,
    load_gnomad_catalog,
)


@dataclass(frozen=True, slots=True)
class ValidationDivergence:
    """
    One record whose coordinates do not match the bundled catalog
    """

    record_id: str
    source: str
    chrom: str
    pos: int
    end: int


@dataclass(frozen=True, slots=True)
class ValidationResult:
    """
    Outcome of a self-consistency validation run
    """

    gnomad_total: int
    gnomad_matched: int
    blacklist_total: int
    blacklist_matched: int
    divergences: tuple[ValidationDivergence, ...]

    @property
    def passed(self) -> bool:
        return not self.divergences


def validate_vcf(vcf_path: str | Path) -> ValidationResult:
    """
    Validate every ``SVFORGE_SOURCE``-tagged record in ``vcf_path``
    """
    gnomad_index = _index_gnomad(load_gnomad_catalog())
    blacklist_index = _index_blacklist(load_blacklist_catalog())

    gnomad_total = 0
    gnomad_matched = 0
    blacklist_total = 0
    blacklist_matched = 0
    divergences: list[ValidationDivergence] = []

    with pysam.VariantFile(str(vcf_path)) as vin:
        for rec in vin:
            source = _source_tag(rec)
            if source is None:
                continue

            chrom = str(rec.chrom)
            pos = int(rec.pos)
            end = _record_end(rec)

            if source == "gnomad":
                gnomad_total += 1
                if _matches_gnomad(chrom, pos, end, gnomad_index):
                    gnomad_matched += 1
                else:
                    divergences.append(
                        ValidationDivergence(
                            record_id=str(rec.id or ""),
                            source=source,
                            chrom=chrom,
                            pos=pos,
                            end=end,
                        )
                    )
            elif source == "blacklist":
                blacklist_total += 1
                if _matches_blacklist(chrom, pos, end, blacklist_index):
                    blacklist_matched += 1
                else:
                    divergences.append(
                        ValidationDivergence(
                            record_id=str(rec.id or ""),
                            source=source,
                            chrom=chrom,
                            pos=pos,
                            end=end,
                        )
                    )

    return ValidationResult(
        gnomad_total=gnomad_total,
        gnomad_matched=gnomad_matched,
        blacklist_total=blacklist_total,
        blacklist_matched=blacklist_matched,
        divergences=tuple(divergences),
    )


def _source_tag(rec: pysam.VariantRecord) -> str | None:
    if "SVFORGE_SOURCE" not in rec.header.info:
        return None
    try:
        value = rec.info.get("SVFORGE_SOURCE")
    except (KeyError, ValueError):
        return None
    if isinstance(value, tuple):
        value = value[0] if value else None
    if value is None:
        return None
    source = str(value).lower()
    if source in {"gnomad", "blacklist"}:
        return source
    return None


def _record_end(rec: pysam.VariantRecord) -> int:
    svtype = _first_info(rec, "SVTYPE")
    if svtype == "BND":
        chr2 = _first_info(rec, "CHR2")
        pos2 = _first_info(rec, "POS2")
        if chr2 is not None and pos2 is not None:
            return _to_int(pos2)
    if svtype == "INS":
        # Manta emits END=POS for insertions; the real end is POS + SVLEN
        svlen = _first_info(rec, "SVLEN")
        if svlen is not None:
            return int(rec.pos) + abs(_to_int(svlen))
    return int(rec.stop)


def _index_gnomad(
    catalog: tuple[GnomadEntry, ...],
) -> dict[tuple[str, int, int], GnomadEntry]:
    return {(e.chrom, e.pos, e.end): e for e in catalog}


def _index_blacklist(
    catalog: tuple[BlacklistEntry, ...],
) -> dict[tuple[str, int, int], BlacklistEntry]:
    return {(e.chrom, e.pos, e.end): e for e in catalog}


def _matches_gnomad(
    chrom: str,
    pos: int,
    end: int,
    index: dict[tuple[str, int, int], GnomadEntry],
) -> bool:
    return (chrom, pos, end) in index


def _matches_blacklist(
    chrom: str,
    pos: int,
    end: int,
    index: dict[tuple[str, int, int], BlacklistEntry],
) -> bool:
    return (chrom, pos, end) in index


def _first_info(rec: pysam.VariantRecord, key: str) -> object:
    if key not in rec.header.info:
        return None
    try:
        value = rec.info.get(key)
    except (KeyError, ValueError):
        return None
    if isinstance(value, tuple):
        return value[0] if value else None
    return value


def _to_int(value: object) -> int:
    if isinstance(value, (int, str, float)):
        return int(value)
    return int(str(value))
